export const projects = [
  {
    title: 'OFFENSIVE SECURITY CODE PROJECTS',
    description: "Offensive security code project creating including : a Port Scanner, Packet capturer, Nmap scan, Brute-Force application and Keylogger. Offensive security is a proactive and adversarial method of preventing assaults on computer systems, networks, and humans.",  
      image: '/images/OSCP.jpg',
      tags: ['Python', 'C#', 'Bash'],
    source: 'https://github.com/AntImmelman/Offensive-Security-Code-Projects',
    visit: 'https://github.com/AntImmelman/Offensive-Security-Code-Projects',
    id: 0,
  },
  {
    title: 'SERVERLESS INFRASTRUCTURE-AS-CODE',
    description:"Provision, build & deploy a serverless applications on AWS with Cloudformation and Terraform. Serverless Architecture is a way to build & run applications, and services without having to manage infrastructure",
    image: '/images/SAIC.jpg',
    tags: ['YAML', 'Cloudformation','Terraform'],
    source: 'https://github.com/AntImmelman/Serverless-Infrastructure-as-Code',
    visit: 'https://github.com/AntImmelman/Serverless-Infrastructure-as-Code',
    id: 1,
  },
  {
    title: 'FACIAL RECOGNITIONING ATTENDANCE STSTEM',
    description: "The system works on face recognition where each student / employee is photographed. The teacher/supervisior can then record the attendance. Built with Python using OpenCV and Facial Recognition libraries",
    image: '/images/FRAS.jpg',
    tags: ['Python', 'OpenCV', 'Numpy'],
    source: 'https://github.com/AntImmelman/Computer-Vision-Research/tree/main/Facial_Recognition_Attendance_System',
    visit: 'https://github.com/AntImmelman/Computer-Vision-Research/tree/main/Facial_Recognition_Attendance_System',
    id: 2,
  },
  {
    title: 'GITHUB WEBSCRAPPER',
    description: "Web scraping, also known as web harvesting or web data extraction, is a type of data scraping that is used to extract information from websites. Enter your Github username to get a profile picture.",
    image: '/images/GithubWebSc.jpg',    
    tags: ['Python', 'OpenCV'],
    source: 'https://github.com/AntImmelman/Social-Engineering',
    visit: 'https://github.com/AntImmelman/Social-Engineering',
    id: 3,
  },

  {
    title: 'DEVSECOPS',
    description: "GitHub Actions makes it simple to automate all of your software workflows, and it now includes world-class CI/CD. You can build, test, and deploy your code directly from GitHub. Integrated testing tools, SCAs, SASTs & DASTs ",
    image: 'images/GIT.jpg',
    tags: ['Github Actions', 'CI','YAML'],
    source: 'https://github.com/AntImmelman/DevSecOps-with-Github-Actions',
    visit: 'https://github.com/AntImmelman/DevSecOps-with-Github-Actions',
    id: 5,
  },
  {
    title: 'NETWORK AUTOMATION',
    description: "Python is widely used for performing network automation and has several modules that allow you to connect to network devices and execute commands and scripts that allow us to run automated recon. AutomationScript.py configures a Cisco network with VLANs, DHCP, HSRP, STP, and OSPF between the layers of the network",
    image: '/images/CISCO.jpg',    
    tags: ['Cisco','Python'],
    source: 'https://github.com/AntImmelman/Network-Automation',
    visit: 'https://github.com/AntImmelman/Network-Automation',
    id: 6,
  },
  {
    title: 'ECR20 TOKEN: LYAM',
    description: "ERC-20 is one of the most important Ethereum tokens. ERC-20 has emerged as the technical standard; it is used for token implementation in all smart contracts on the Ethereum blockchain and provides a set of rules that all Ethereum-based tokens must follow.",
    image: '/images/ETH.jpg',
    tags: ['Solidity'],
    source: 'https://github.com/AntImmelman/ECR20-token',
    visit: 'https://github.com/AntImmelman/ECR20-token',
    id: 4,
  },
  {
    title: 'SIMPLE NEURAL NETWORK',
    description: "This simple neural network is designed to predict one outcome from three different input values using mathematical equations and the naturally occurring physiological model of inputs and outputs through a neuron via synapses.",
    image: '/images/NN.jpg',
    tags: ['Python', 'Numpy'],
    source: 'https://github.com/AntImmelman/Neural-Network',
    visit: 'https://github.com/AntImmelman/Neural-Network',
    id: 7,
  },
];

export const TimeLineData = [
  { year: 2016, text: 'Studied Mechatronics Engineering', },
  { year: 2016, text: 'Apprentinceship at EMS technic', },
  { year: 2017, text: 'Studied Computer Systems Engineering at CUT', },
  { year: 2018, text: 'Started as a IT freelancer while still at CUT', },
  { year: 2019, text: 'Studied IT Systems Administartor at CTU', },
  { year: 2020, text: 'Studied Cloud & Cybersecurity Professional at CTU', },
  { year: 2020, text: 'Part-time Computer Vision Researcher internship at KFT', },
  { year: 2021, text: 'Started as a Backend developer at Bettr and changed to Cybersecurity Engineer', },
  { year: 2022, text: 'Cybersecurity Engineer at Bettr', },
];